Stock_Management_System/Areas/Stocks/Models/AddStockModel.cs
using Newtonsoft.Json;
using Stock_Management_System.Areas.Accounts.Models;
using System.ComponentModel.DataAnnotations;

namespace Stock_Management_System.Areas.Stocks.Models
{
   
    public class Purchase_Stock
    {
        public int PurchaseStockId { get; set; }
        public DateTime PurchaseStockDate { get; set; }
        public int? CustomerId { get; set; }

        public string? CustomerName { get; set; }

        public string? CustomerAddress { get; set; }

        public string? CustomerType { get; set; }


        
        public int ProductId { get; set; }


        public string? ProductName { get; set; }
        public int? ProductGradeId { get; set; }
        public string? ProductGrade { get; set; }

     
        public string? PurchaseStockLocation { get; set; }
        public decimal? Bags { get; set; }
        public decimal? BagPerKg { get; set; }

    
        public decimal? TotalWeight { get; set; }

        [Required]
        public decimal ProductPrice { get; set; }

        
        public decimal TotalPrice { get; set; }

        public int VehicleId { get; set; }
        public string? VehicleName { get; set; }


        public string? VehicleNo { get; set; }

        public string? DriverName { get; set; }

       
        public string? TolatName { get; set; }
        public string? PaymentStatus { get; set; }
    }


    public class Show_Purchase_Stock
    {
        public int PurchaseStockId { get; set; }
        public DateTime PurchaseStockDate { get; set; }
        public int? CustomerId { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerType { get; set; }

        public string? CustomerAddress { get; set; }

        public string? CustomerPhoneNo { get; set; }

        public int ProductId { get; set; }
        public string? ProductName { get; set; }
        public int? ProductGradeId { get; set; }
        public string? ProductGrade { get; set; }
        public string? PurchaseStockLocation { get; set; }
        public decimal? Bags { get; set; }
        public decimal? BagPerKg { get; set; }
        public decimal? TotalWeight { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public int VehicleId { get; set; }
        public string? VehicleName { get; set; }
        public string? VehicleNo { get; set; }
        public string? DriverName { get; set; }
        public string? TolatName { get; set; }
        public string? PaymentStatus { get; set; }
    }

    public class Insert_And_Update_Purchase_Stock
    {
        public int PurchaseStockId { get; set; }
        public DateTime PurchaseStockDate { get; set; }

        [Required(ErrorMessage ="Please Select Product")]
        public int ProductId { get; set; }
        public int? ProductGradeId { get; set; }

        [Required(ErrorMessage ="Please Enter Location !")]
        public string? PurchaseStockLocation { get; set; }
        public decimal? Bags { get; set; }
        public decimal? BagPerKg { get; set; }

        [Required(ErrorMessage = "Please Enter Weight Or Enter Bag And Bags Per Kg And Get Weight")]
        public decimal? TotalWeight { get; set; }

        [Required(ErrorMessage = "Please Enter Product Price")]
        public decimal ProductPrice { get; set; }

        [Required(ErrorMessage = "Please Enter Total Price")]
        public decimal TotalPrice { get; set; }

        [Required(ErrorMessage = "Please Select Vehicle Type")]
        public int VehicleId { get; set; }
        public string? VehicleName { get; set; }

        [Required(ErrorMessage = "Please Enter Vehicle No")]
        public string? VehicleNo { get; set; }

        [Required(ErrorMessage = "Please Enter Driver Name")]
        public string? DriverName { get; set; }

      
        public string? TolatName { get; set; }
        public string? PaymentStatus { get; set; }
    }


    public class Customers_Stock_Combined_Model
    {
        [JsonProperty("purchase_Stock")]
        public Insert_And_Update_Purchase_Stock Insert_Purchase_Stock { get; set; }

        [JsonProperty("customers_Model")]
        public Customer_Model Customers { get; set; }



    }

}

Stock_Management_System/Areas/Stocks/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Stock_Management_System.Areas.Stocks.Models;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.Text;
using Newtonsoft.Json;
using Stock_Management_System.UrlEncryption;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using ClosedXML.Excel;
using Stock_Management_System.API_Services;
using Stock_Management_System.All_DropDowns;
using Microsoft.AspNetCore.Mvc.Rendering;
using Customers_Model = Stock_Management_System.Areas.Accounts.Models.Customer_Model;
using Stock_Management_System.Areas.Accounts.Models;
using Stock_Management_System.Services;
using Stock_Management_System.BAL;

namespace Stock_Management_System.Areas.Stocks.Controllers
{

    [Area("Stocks")]
    [Route("~/[controller]/[action]")]
    [CheckAccess]
    public class StockController : Controller
    {

        #region Section: Constructor and Configuration

        public IConfiguration Configuration;

        Uri baseaddress = new Uri("https://stock-manage-api-shree-ganesh-agro-ind.somee.com/api");

        public readonly HttpClient _Client;

        private readonly Api_Service api_Service = new Api_Service();

        public HttpContextAccessor _HttpContextAccessor;

        /// <summary>
        /// Initializes a new instance of the <see cref="StockController"/> class.
        /// </summary>
        /// <param name="configuration">Configuration settings to be used by the controller.</param>
        /// <remarks>
        /// Sets up the HttpClient with a base address and initializes the Api_Service.
        /// </remarks>
        public StockController(IConfiguration configuration)
        {
            Configuration = configuration;

            _Client = new HttpClient();
            _Client.BaseAddress = baseaddress;
            _HttpContextAccessor = new HttpContextAccessor();

        }

        #endregion

        #region Section: Dropdown Function

        /// <summary>
        /// Populates dropdown lists for the stock views.
        /// </summary>

        public async Task PopulateDropdownLists()
        {
            DropDown_Model dropDown_Model = await new DropDowns_Class().GetAllDropdownsAsync();
            if (dropDown_Model != null)
            {
                ViewBag.Products = new SelectList(dropDown_Model.Products_DropDowns_List, "ProductId", "ProductNameInGujarati");
                ViewBag.ProductsInEnglish = new SelectList(dropDown_Model.Products_DropDowns_List, "ProductId", "ProductNameInEnglish");
                ViewBag.ProductGrade = new SelectList(dropDown_Model.Products_Grade_DropDowns_List, "ProductGradeId", "ProductGrade");
                ViewBag.Vehicle = new SelectList(dropDown_Model.Vehicle_DropDowns_List, "VehicleId", "VehicleName");
            }
        }

        #endregion

        #region Section: Add Purchase Stock

        /// <summary>
        /// Initiates the process to add a new stock entry.
        /// </summary>

        public async Task<IActionResult> AddStock()
        {

            await PopulateDropdownLists();

            return View();
        }

        /// <summary>
        /// Adds details for a new stock entry.
        /// </summary>

        public async Task<IActionResult> InsertStockAndCustomerDetails(Customers_Stock_Combined_Model model)
        {
            // Check if the customer is new; if so, add them
            if (model.Customers.CustomerId == 0)
            {
                // Add the new customer and directly use the returned model
                Customer_Model customerInfo = await CreateCustomer(model.Customers);
                if (customerInfo == null || customerInfo.CustomerId == 0)
                {
                    return BadRequest("Failed to create a new customer.");
                }
                model.Customers = customerInfo; // Update the model with the new customer info
            }

            // Prepare the data object for updating stock details
            var dataObject = new
            {
                purchase_Stock = model.Insert_Purchase_Stock,
                customers_Model = model.Customers // Use the updated/existing customer details
            };

            // Serialize the data object to JSON
            var jsonContent = JsonConvert.SerializeObject(dataObject);
            var stringContent = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));

            // Send the PUT request to the "Stock/Update_Purchase_Stock" endpoint
            HttpResponseMessage response = await _Client.PostAsync($"{_Client.BaseAddress}/Stock/AddPurchaseStockWithCustomerDetails", stringContent);

            if (response.IsSuccessStatusCode)
            {
                return Json(new
                {
                    redirectUrl = Url.Action("Stocks")
                });
            }
            else
            {
                // Handle failures, possibly returning an error status or message
                return StatusCode((int)response.StatusCode, "Error message here");
            }

        }

        #endregion

        #region Section: Update Purchase Stock

        public async Task<IActionResult> EditStock(string TN_ID, string Customer_ID)
        {

            await PopulateDropdownLists();

            Customers_Stock_Combined_Model customers_Stock_Combined_Model = new Customers_Stock_Combined_Model();

            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));

            HttpResponseMessage response = await _Client.GetAsync($"{_Client.BaseAddress}/Stock/GetPurchaseStockAndCustomerDetails/{UrlEncryptor.Decrypt(TN_ID)}&{UrlEncryptor.Decrypt(Customer_ID)}");

            if (response.IsSuccessStatusCode)
            {

                string data = await response.Content.ReadAsStringAsync();
                dynamic jsonObject = JsonConvert.DeserializeObject(data);
                var dataObject = jsonObject.data;
                var extractedDataJson = JsonConvert.SerializeObject(dataObject, Formatting.Indented);
                customers_Stock_Combined_Model = JsonConvert.DeserializeObject<Customers_Stock_Combined_Model>(extractedDataJson);

            }

            return View(customers_Stock_Combined_Model);

        }

        public async Task<IActionResult> UpdateStockAndCustomerDetails(Customers_Stock_Combined_Model model)
        {

            // Check if the customer is new; if so, add them
            if (model.Customers.CustomerId == 0)
            {
                // Add the new customer and directly use the returned model
                Customer_Model customerInfo = await CreateCustomer(model.Customers);
                if (customerInfo == null || customerInfo.CustomerId == 0)
                {
                    return BadRequest("Failed to create a new customer.");
                }
                model.Customers = customerInfo; // Update the model with the new customer info
            }

            // Prepare the data object for updating stock details
            var dataObject = new
            {
                purchase_Stock = model.Insert_Purchase_Stock,
                customers_Model = model.Customers // Use the updated/existing customer details
            };

            // Serialize the data object to JSON
            var jsonContent = JsonConvert.SerializeObject(dataObject);
            var stringContent = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));

            // Send the PUT request to the "Stock/Update_Purchase_Stock" endpoint
            HttpResponseMessage response = await _Client.PutAsync($"{_Client.BaseAddress}/Stock/UpdatePurchaseStock", stringContent);

            if (response.IsSuccessStatusCode)
            {
                return Json(new
                {
                    redirectUrl = Url.Action("Stocks")
                });
            }
            else
            {
                // Handle failures, possibly returning an error status or message
                return StatusCode((int)response.StatusCode, "Error message here");
            }
        }

        #endregion

        #region Section: Get Customer Details From AutoComplete

        /// <summary>
        /// Retrieves customer data by name for autocomplete feature.
        /// </summary>
        private async Task<Customer_Model> GetCustomerProfile(int Customer_ID, string Customer_Type)
        {
            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));

            HttpResponseMessage response = await _Client.GetAsync($"{_Client.BaseAddress}/Customers/GetCustomerByIDAndType/{Customer_ID}&{Customer_Type}");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                dynamic jsonObject = JsonConvert.DeserializeObject(data);
                Customer_Model customerInfo = JsonConvert.DeserializeObject<Customer_Model>(JsonConvert.SerializeObject(jsonObject.data, Formatting.Indented));
                return customerInfo;
            }
            return null;
        }

        /// <summary>
        /// Asynchronously gets a list of customer models matching a specified name, intended for use with an autocomplete feature.
        /// </summary>
        /// <param name="CustomerName">The name of the customer to search for.</param>

Stock_Management_System/Areas/Stocks/Views/Stock/AddStock.cshtml
@using System.Data;
@model Stock_Management_System.Areas.Stocks.Models.Customers_Stock_Combined_Model;
@{
    ViewData["Title"] = "Add Stock";
}

<div class="content">
    <div class="page-header">
        <div class="page-title">
            <h4>Add Stock</h4>
            <h6 style="font-style:initial; font-weight:bolder;color:gray">Add/Existing Stock</h6>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <form id="AddStockForm" class="row g-3" asp-action="InsertStockAndCustomerDetails" asp-controller="Stock" onsubmit="return CheckData()" method="post">
                <!-- Date -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: black;">*</span> Stock Date
                        </label>
                        <input type="date" placeholder="DD-MM-YYYY" id="datepicker" asp-for="Insert_Purchase_Stock.PurchaseStockDate" class="form-control">
                    </div>
                </div>
                <!-- Stock Type -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: black;">*</span> Select Grade
                        </label>
                        <select class="select" id="stockgrade" aria-label="stockgrade" asp-for="Insert_Purchase_Stock.ProductGradeId" asp-items="ViewBag.ProductGrade">
                            <option selected disabled>-- Stock Grade --</option>
                        </select>
                    </div>
                </div>
                <!-- Grain Type -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: red;">*</span> Select Product Type
                        </label>
                        <select class="select" id="selectgrain" aria-label="graintype" asp-for="Insert_Purchase_Stock.ProductId" asp-items="ViewBag.Products">
                            <option value="" selected disabled>-- Select Grain --</option>
                        </select>
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.ProductId"></span>
                    </div>
                </div>
                <input type="hidden" id="CustomerId" asp-for="Customers.CustomerId" />
                <!-- Customer Name -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: red;">*</span> Customer Name
                        </label>
                        <input type="text" class="form-control" id="Customer" placeholder="Customer Name" asp-for="Customers.CustomerName" oninput="this.value = this.value.toUpperCase()">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Customers.CustomerName"></span>
                        <span id="newCustomerMessage" value="NewCustomer" style="color:green">* New Customer</span>
                    </div>
                </div>
             
                <div id="newcustomertype" class="col-lg-3 col-sm-6 col-12" style="display: none;">
                    <div class="form-group">
                        <label>
                            <span style="color: red;">*</span> New Customer Type
                        </label>
                        <input type="text" class="form-control" placeholder="Customer Type" value="BUYER" name="CustomerType" disabled id="cttype" asp-for="Customers.CustomerType" oninput="this.value = this.value.toUpperCase()">
                        <input type="hidden" name="Customers.CustomerType" value="BUYER">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Customers.CustomerType"></span>
                    </div>
                </div>

                <!-- Customer City -->
                <div id="newcustomercity" class="col-lg-3 col-sm-6 col-12" style="display: none;">
                    <div class="form-group">
                        <label for="ctname">
                            <span style="color: red;">*</span> New Customer City
                        </label>
                        <input type="text" class="form-control" placeholder="City Name" id="customercity" asp-for="Customers.CustomerAddress" oninput="this.value = this.value.toUpperCase()">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Customers.CustomerAddress"></span>
                    </div>
                </div>
                <!-- Customer Contact_No -->
                <div id="newcustomerphoneno" class="col-lg-3 col-sm-6 col-12" style="display: none;">
                    <div class="form-group">
                        <label for="bags">
                            <span style="color: red;">*</span> Enter Customer No
                        </label>
                        <input type="number" inputmode="numeric" class="form-control" placeholder="Contact No" asp-for="Customers.CustomerContact" id="contactno">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Customers.CustomerContact"></span>
                    </div>
                </div>
                <!-- Customer Good Taken Loaction -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: red;">*</span> Stock Taken Place
                        </label>
                        <input type="text" class="form-control" placeholder="Enter Location" asp-for="Insert_Purchase_Stock.PurchaseStockLocation" id="goodtakenloc" oninput="this.value = this.value.toUpperCase()">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.PurchaseStockLocation"></span>
                    </div>
                </div>
                <!-- Tolat Name -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: black;">*</span> Tolat Name
                        </label>
                        <input type="text" class="form-control" placeholder="Tolat Name" asp-for="Insert_Purchase_Stock.TolatName" id="tolatname" oninput="this.value = this.value.toUpperCase()">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.TolatName"></span>
                    </div>
                </div>
                <!-- Bags -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label>
                            <span style="color: black;">*</span> Bags
                        </label>
                        <input type="number" inputmode="numeric" class="form-control" placeholder="Bags" id="bags" oninput="CalculateMethod()" asp-for="Insert_Purchase_Stock.Bags">
                    </div>
                </div>
                <!-- Bags Per KG -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="bagsperkg">
                            <span style="color: black;">*</span> Bags Per KG
                        </label>
                        <input type="number" inputmode="numeric" class="form-control" placeholder="Bags per KG" id="bagsperkg" oninput="CalculateMethod()" asp-for="Insert_Purchase_Stock.BagPerKg">
                    </div>
                </div>
                <!-- Weight -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="weight">
                            <span style="color: red;">*</span> Weight
                        </label>
                        <input type="number" inputmode="numeric" class="form-control" placeholder="Weight" id="weight" asp-for="Insert_Purchase_Stock.TotalWeight">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.TotalWeight"></span>
                    </div>
                </div>
                <!-- Product Price -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="productprice">
                            <span style="color: red;">*</span> Enter Product Price ⟨₹⟩
                        </label>
                        <input type="number" inputmode="numeric" class="form-control" placeholder="Product Price ⟨₹⟩" id="productprice" oninput="CalculateMethod()" asp-for="Insert_Purchase_Stock.ProductPrice">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.ProductPrice"></span>
                    </div>
                </div>
                <!-- Total Price -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="totalprice">
                            <span style="color: red;">*</span> Total Price ⟨₹⟩
                        </label>
                        <input type="number" inputmode="numeric" class="form-control" placeholder="Total Price ⟨₹⟩" id="totalprice" asp-for="Insert_Purchase_Stock.TotalPrice">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.TotalPrice"></span>
                    </div>
                </div>
                <!-- Vehicle Type -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="selectvehicletype">
                            <span style="color: red;">*</span> Select Vehicle
                        </label>
                        <select class="select" id="selectvehicletype" aria-label="vehicletype" asp-for="Insert_Purchase_Stock.VehicleId" asp-items="@(ViewBag.Vehicle)">
                            <option selected disabled>-- Select Vehicle --</option>
                        </select>
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.VehicleId"></span>
                    </div>
                </div>

                <!-- Vehicle No. -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="vehicleno">
                            <span style="color: red;">*</span> Vehicle No.
                        </label>
                        <input type="text" class="form-control" placeholder="GJ-01-MH-1234" id="vehicleno" asp-for="Insert_Purchase_Stock.VehicleNo" oninput="formatVehicleNo(this)">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.VehicleNo"></span>
                    </div>
                    <span id="error-msg" style="color: red; font-size:11px; font-weight:bold;"></span>
                </div>
                <!-- Driver Name -->
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="drivername">
                            <span style="color: red;">*</span> Driver Name
                        </label>
                        <input type="text" class="form-control" placeholder="Driver Name" asp-for="Insert_Purchase_Stock.DriverName" id="drivername" oninput="this.value = this.value.toUpperCase()">
                        <span class="text-danger" style="color: red; font-size:11px; font-weight:bold;" asp-validation-for="Insert_Purchase_Stock.DriverName"></span>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-auto text-center mb-3" style="margin-top:20px;">
                        <button type="submit" class="btn btn-success me-2">
                            <i class="fas fa-plus"></i> Add Stock
                        </button>
                        <button type="reset" onclick="confirmStockDataReset()" class="btn btn-danger">
                            <i class="fas fa-trash"></i> Clear All
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Load jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
@section Scripts {
    <script src="/js/bundle/stock/add-bundle.js"></script>"
}

Stock_Management_System/Areas/Stocks/Views/Stock/Added_Stock_Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Details Stock";

    DateTime? invoiceDate = Model.PurchaseStockDate;
    DateTime? onlyDate = invoiceDate?.Date;

    string? formattedDate = onlyDate?.ToString("dd-MM-yyyy");
}

@model Stock_Management_System.Areas.Stocks.Models.Purchase_Stock;

<style>
    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px;
    }

    th, td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    .scrollable-table {
        overflow-x: auto;
        display: block;
        white-space: nowrap;
    }

</style>

<div class="container">
    <br />
    <div class="row">
        <!-- Left side - Back link -->
        <div class="col-2">
            <a asp-action="Manage_Stocks" asp-controller="Stock" class="text-decoration-none">
                <i class="fa fa-arrow-left" style="color:green; transform: scale(1.25);"> </i>
            </a>
        </div>

        <!-- Center - Invoice Details -->
        <div class="col-8 text-center">
            <h5>Stock Details</h5>
        </div>





        <br />
        <div class="table-responsive scrollable-table table-responsive-sm">
            <table class="table">
                @*  <tr>
                <th>Transaction ID</th>
                <td>@Model.PurchaseStockId</td>
                </tr> *@
                <tr>
                    <th>Date</th>
                    <td>@formattedDate</td>
                </tr>
                <tr>
                    <th>Customer Name</th>
                    <td>@Model.CustomerName</td>
                </tr>

                <tr>
                    <th>Customer Type</th>
                    <td>@Model.CustomerType</td>
                </tr>


                <tr>
                    <th>Product Name</th>
                    <td>@Model.ProductName</td>
                </tr>

                <tr>
                    <th>Goods Taken Loaction</th>
                    <td>@Model.PurchaseStockLocation</td>
                </tr>

                <tr>
                    <th>Bag</th>
                    <td>@(Model.Bags == 0 ? "--" : Model.Bags.ToString()) </td>
                </tr>
                <tr>
                    <th>Bag Per Kg</th>
                    <td>@(Model.BagPerKg == 0 ? "--" : Model.BagPerKg.ToString()) </td>
                </tr>
                <tr>
                    <th>Weight</th>
                    <td>@Model?.TotalWeight</td>
                </tr>
                <tr>
                    <th>Product Price(₹)</th>
                    <td>@Model?.ProductPrice.ToString("C")</td>
                </tr>
                <tr>
                    <th>Total Price(₹)</th>
                    <td>@Model?.TotalPrice.ToString("C")</td>
                </tr>
                <tr>
                    <th>Vehicle Type</th>
                    <td>@Model?.VehicleName</td>
                </tr>
                <tr>
                    <th>Vehicle No.</th>
                    <td>@Model?.VehicleNo</td>
                </tr>
                <tr>
                    <th>Driver Name</th>
                    <td>@Model?.DriverName</td>
                </tr>
                <tr>
                    <th>Tolat Name</th>
                    <td>@Model?.TolatName</td>
                </tr>
                <tr>
                    <th>Stock Grade</th>
                    <td>@(string.IsNullOrWhiteSpace(Model?.ProductGrade) ? "--" : Model?.ProductGrade)</td>
                </tr>




            </table>
        </div>
    </div>