Stock_Management_System/Areas/Sales/Models/SalesModel.cs
using Newtonsoft.Json;
using Stock_Management_System.Areas.Accounts.Models;
using System.ComponentModel.DataAnnotations;

namespace Stock_Management_System.Areas.Sales.Models
{
    public class SaleModel
    {
        public int SaleId { get; set; }

        public DateTime Create_Sales { get; set; }

        [Required(ErrorMessage ="Please Select Product")]
        public int Product_Id { get; set; }

        [Required(ErrorMessage ="Please Select Receive Payment Date")]
        public DateTime Receive_Payment_Date { get; set; }


        public string? Product_Name { get; set; }

        [Required(ErrorMessage ="Please Enter Brand Name")]
        public string? Brand_Name { get; set; }

        [Required(ErrorMessage ="Plese Select Payment Method")]
        public string? Payment_Method { get; set; }

        public int Receive_Bank_Id { get; set; }


        [Required(ErrorMessage ="Please Select Bank")]
        public int? Receive_Information_Id { get; set; }


        public decimal? Bags { get; set; }

        public decimal? BagPerKg { get; set; }

        [Required(ErrorMessage ="Please Enter Weight or Enter Bag and Bag Per Kg Get Weight")]
        public decimal? Total_Weight { get; set; }

        [Required(ErrorMessage ="Please Enter Rate")]
        public decimal Rate { get; set; }

        [Required(ErrorMessage ="Total Price Not Empty")]
        public decimal Total_Price { get; set; }

        [Required(ErrorMessage ="Please Enter Receive Amount")]
        public decimal Receive_Amount { get; set; }


        public decimal? CGST { get; set; }

        public decimal? SGST { get; set; }

        public decimal? TotalCGSTPrice { get; set; }

        public decimal? TotalSGSTPrice { get; set; }

        public decimal? WithoutGSTPrice { get; set; }


        public decimal? Discount { get; set; }

        public decimal? Deducted_Amount { get; set; }

        [Required(ErrorMessage ="Please Select Full Payment Receive or Not !")]
        public string? IsFullPaymentReceive { get; set; }


        [Required(ErrorMessage ="Please Select Remain Payment Date")]
        public DateTime? Remain_Payment_Date { get; set; }
        [Required(ErrorMessage = "Please Enter Remain Payment Amount")]
        public decimal? Receive_Remain_Amount { get; set; }
        [Required(ErrorMessage = "Please Select Remain Payment Method")]
        public string? Remain_Payment_Method { get; set; }


        public int? Remain_Amount_Receive_Bank_Id { get; set; }

        public int? Remain_Infromation_ID { get; set; }




    }

    public class Sale_Customer_Combied_Model
    {
        [JsonProperty("customer")]
        public Customer_Model customer { get; set; }

        [JsonProperty("sale")]
        public SaleModel sale { get; set; }
    }

    public class Show_Sale
    {
        public int saleId { get; set; }
        public DateTime Create_Sales { get; set; }
        public int Product_Id { get; set; }

        public int? CustomerId { get; set; }

        public string? CustomerName { get; set; }

        public string? CustomerType { get; set; }


        public DateTime Receive_Payment_Date { get; set; }

        public string? Product_Name { get; set; }

        public string? Brand_Name { get; set; }

        public string? Payment_Method { get; set; }

        public int? Receive_Information_ID { get; set; }

        public string? Receive_Account_No { get; set; }

        public string? Account_Holder_Name { get; set; }

        public string? Bank_Icon { get; set; }

        public decimal? Bags { get; set; }

        public decimal? BagPerKg { get; set; }


        public decimal? Total_Weight { get; set; }

        public decimal Rate { get; set; }

        public decimal? CGST { get; set; }

        public decimal? SGST { get; set; }

        public decimal? TotalCGSTPrice { get; set; }

        public decimal? TotalSGSTPrice { get; set; }

        public decimal? WithoutGSTPrice { get; set; }

        public decimal Total_Price { get; set; }

        public decimal Receive_Amount { get; set; }

        public decimal? Discount { get; set; }

        public decimal? Deducted_Amount { get; set; }

        public string? IsFullPaymentReceive { get; set; }

        public DateTime? Remain_Payment_Date { get; set; }

        public decimal? Receive_Remain_Amount { get; set; }

        public string? Remain_Payment_Method { get; set; }

        public int? Remain_Receive_Information_ID { get; set; }

        public string? Receive_Remain_Account_No { get; set; }

        public string? Remain_Account_Holder_Name { get; set; }

        public string? Remain_Bank_Icon { get; set; }

    }
}

Stock_Management_System/Areas/Sales/Controllers/SaleController.cs
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Stock_Management_System.All_DropDowns;
using Stock_Management_System.API_Services;
using Stock_Management_System.Areas.Accounts.Models;
using Stock_Management_System.Areas.Manage.Models;
using Stock_Management_System.Areas.Sales.Models;
using Stock_Management_System.Areas.Stocks.Models;
using Stock_Management_System.BAL;
using Stock_Management_System.UrlEncryption;

using System.Text;
using static Stock_Management_System.Areas.Manage.Models.Payment_All_Models;

namespace Stock_Management_System.Areas.Sales.Controllers
{
    [Area("Sales")]
    [Route("~/[controller]/[action]")]
    [CheckAccess]
    public class SaleController : Controller
    {
        public IConfiguration Configuration;

        Uri baseaddress = new Uri("https://stock-manage-api-shree-ganesh-agro-ind.somee.com/api");

        public readonly HttpClient _Client;

        public Api_Service api_Service = new Api_Service();

        public HttpContextAccessor _HttpContextAccessor;

        public SaleController(IConfiguration configuration)
        {
            Configuration = configuration;
            _Client = new HttpClient();
            _Client.BaseAddress = baseaddress;
            _HttpContextAccessor = new HttpContextAccessor();
        }

        #region Section: Dropdown Function

        /// <summary>
        /// Populates dropdown lists for the stock views.
        /// </summary>

        public async Task PopulateDropdownLists()
        {
            DropDown_Model dropDown_Model = await new DropDowns_Class().GetAllDropdownsAsync();
            if (dropDown_Model != null)
            {
                ViewBag.Products = new SelectList(dropDown_Model.Products_DropDowns_List, "ProductId", "ProductNameInGujarati");
                ViewBag.ProductsInEnglish = new SelectList(dropDown_Model.Products_DropDowns_List, "ProductId", "ProductNameInEnglish");
                ViewBag.ProductGrade = new SelectList(dropDown_Model.Products_Grade_DropDowns_List, "ProductGradeId", "ProductGrade");
                ViewBag.Vehicle = new SelectList(dropDown_Model.Vehicle_DropDowns_List, "VehicleId", "VehicleName");
            }

            // Bank 

            List<Our_Banks_Dropdown> bank_Models = await api_Service.List_Of_Data_Display<Our_Banks_Dropdown>("Bank/GetOurBanksSelectList");

            if (bank_Models != null)
            {
                // Base URL where the images are hosted, ensure this matches the actual location
                string baseUrl = "https://stock-manage-api-shree-ganesh-agro-ind.somee.com/";

                // Append the base URL to each bank's icon path
                foreach (var bank in bank_Models)
                {
                    if (!string.IsNullOrEmpty(bank.BankIcon))
                    {
                        bank.BankIcon = baseUrl + bank.BankIcon;
                    }
                }

                ViewBag.OurBanks = bank_Models;
            }
        }

        #endregion

        #region Section: Add Sale

        /// <summary>
        /// Displays the view to add a new sale.
        /// </summary>
        public async Task<IActionResult> AddSale()
        {

            await PopulateDropdownLists();

            return View();
        }

        /// <summary>
        /// Inserts a new sale into the system along with customer details.
        /// </summary>
        /// <param name="model">Combined model of sale and customer data.</param>
        public async Task<IActionResult> InsertSale(Sale_Customer_Combied_Model model)
        {
            // Check if the customer is new; if so, add them
            if (model.customer.CustomerId == 0)
            {
                // Add the new customer and directly use the returned model
                Customer_Model customerInfo = await CreateCustomer(model.customer);
                if (customerInfo == null || customerInfo.CustomerId == 0)
                {
                    return BadRequest("Failed to create a new customer.");
                }
                model.customer = customerInfo; // Update the model with the new customer info
            }
            else
            {
                // Fetch existing customer details if not adding new customer
                model.customer = await GetCustomerProfile(model.customer.CustomerId, model.customer.CustomerType);
                if (model.customer == null)
                {
                    return NotFound("Customer not found.");
                }
            }

            // Prepare the data object for posting sale details
            var dataObject = new
            {
                sale = model.sale,
                customer = model.customer // Use the updated/existing customer details
            };

            // Serialize the data object to JSON
            var jsonContent = JsonConvert.SerializeObject(dataObject);
            var stringContent = new StringContent(jsonContent, Encoding.UTF8, "application/json");


            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));


            // Post the model to the "Sales/AddSale" endpoint
            HttpResponseMessage response = await _Client.PostAsync($"{_Client.BaseAddress}/Sale/AddSale", stringContent);
            if (response.IsSuccessStatusCode)
            {
                return Json(new
                {
                    success = true,
                    redirectUrl = Url.Action("Sales")
                });
            }
            else
            {
                return Json(new
                {
                    success = false,
                    redirectUrl = Url.Action("AddSale")
                });
            }
        }


        #endregion

        #region Section: Update Sale

        /// <summary>
        /// Displays the view for editing a sale and its associated customer.
        /// </summary>
        /// <param name="Sale_ID">Encrypted ID of the sale.</param>
        /// <param name="Customer_ID">Encrypted ID of the customer associated with the sale.</param>

        public async Task<IActionResult> EditSale(string Sale_ID, string Customer_ID)
        {

            await PopulateDropdownLists();

            Sale_Customer_Combied_Model sale_Customer_Combied_Model = new Sale_Customer_Combied_Model();

            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));

            HttpResponseMessage response = await _Client.GetAsync($"{_Client.BaseAddress}/Sale/GetSaleAndCustomerDetails/{UrlEncryptor.Decrypt(Sale_ID)}&{UrlEncryptor.Decrypt(Customer_ID)}");

            if (response.IsSuccessStatusCode)
            {

                string data = await response.Content.ReadAsStringAsync();

                var settings = new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                };
                

                dynamic jsonObject = JsonConvert.DeserializeObject(data,settings);
                var dataObject = jsonObject.data;
                var extractedDataJson = JsonConvert.SerializeObject(dataObject, Formatting.Indented);
                sale_Customer_Combied_Model = JsonConvert.DeserializeObject<Sale_Customer_Combied_Model>(extractedDataJson);

            }

            return View(sale_Customer_Combied_Model);

        }

        /// <summary>
        /// Updates the details of an existing sale and customer in the system.
        /// </summary>
        /// <param name="model">Combined model of sale and customer data.</param>
        public async Task<IActionResult> UpdateSaleDetails(Sale_Customer_Combied_Model model)
        {
            // Check if the customer is new; if so, add them
            if (model.customer.CustomerId == 0)
            {
                // Add the new customer and directly use the returned model
                Customer_Model customerInfo = await CreateCustomer(model.customer);
                if (customerInfo == null || customerInfo.CustomerId == 0)
                {
                    return BadRequest("Failed to create a new customer.");
                }
                model.customer = customerInfo; // Update the model with the new customer info
            }
            else
            {
                // Fetch existing customer details if not adding new customer
                model.customer = await GetCustomerProfile(model.customer.CustomerId, model.customer.CustomerType);
                if (model.customer == null)
                {
                    return NotFound("Customer not found.");
                }
            }

            // Prepare the data object for posting sale details
            var dataObject = new
            {
                sale = model.sale,
                customer = model.customer // Use the updated/existing customer details
            };

            // Serialize the data object to JSON
            var jsonContent = JsonConvert.SerializeObject(dataObject);
            var stringContent = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            _Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _HttpContextAccessor.HttpContext.Session.GetString("JWT_Token"));

            // Post the model to the "Sales/AddSale" endpoint
            HttpResponseMessage response = await _Client.PutAsync($"{_Client.BaseAddress}/Sale/UpdateSale", stringContent);
            if (response.IsSuccessStatusCode)
            {
                return Json(new
                {
                    success = true,
                    redirectUrl = Url.Action("Sales")
                });

Stock_Management_System/Areas/Sales/Views/Sale/SaleDetailsView.cshtml
@using System.Globalization
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Sale Details";
}

@model Stock_Management_System.Areas.Sales.Models.Show_Sale;

<link rel="stylesheet" href="~/css/detailsviewtablestyle.css">
<style>

    img.bank-icon {
        width: 20px;
        height: 20px;
        margin-right: 5px;
    }
</style>

<!-- Include html2canvas from CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.3.2/html2canvas.min.js"></script>

<!-- Your custom script file -->
<script src="/js/bundle/sale/details-bundle.js"></script>


<div class="container">
    <br />
    <div class="row">
        <div class="col-2">
            <a asp-action="Sales" asp-controller="Sale" class="text-decoration-none">
                <i class="fa fa-arrow-left" style="color:green; transform: scale(1.25);"></i> 
            </a>
        </div>
        <div class="col-8 text-center">
            <h5>Sale Details</h5>
        </div>
        
        <div class="col-2 text-right">
            <a role="button" id="downloadImage" class="btn icon-button">
                <i class="fa fa-download" aria-hidden="true" style="color:green; transform: scale(1.25);"></i>
            </a>
        </div>
    </div>

    <div class="table-responsive scrollable-table">
        <table class="table">
            @* Display sale creation date and other details *@
            <tr>
                <th>Sale Creation Date</th>
                <td id="saleDate">@Model.Create_Sales.ToString("dd-MM-yyyy")</td>
            </tr>
            <tr>
                <th>Received Payment Date</th>
                <td>@Model.Receive_Payment_Date.ToString("dd-MM-yyyy")</td>
            </tr>
            <tr>
                <th>Customer Name</th>
                <td id="customerName">@Model.CustomerName</td>
            </tr>
            <tr>
                <th>Customer Type</th>
                <td>@Model.CustomerType</td>
            </tr>
            <tr>
                <th>Product Name</th>
                <td>@Model.Product_Name</td>
            </tr>
            @if (!string.IsNullOrEmpty(Model.Brand_Name))
            {
                <tr>
                    <th>Brand Name</th>
                    <td id="brandName">@Model.Brand_Name</td>
                </tr>
            }
            <tr>
                <th>Bag</th>
                <td>@(Model.Bags?.ToString() ?? "--")</td>
            </tr>
            <tr>
                <th>Bag Per Kg</th>
                <td>@(Model.BagPerKg?.ToString() ?? "--")</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>@Model.Total_Weight</td>
            </tr>
            <tr>
                <th>Rate(₹)</th>
                <td>@Model.Rate.ToString("C", new CultureInfo("hi-IN"))</td>
            </tr>
            
            @if(Model.CGST != 0 || Model.CGST != null)
            {
                <tr>
                    <th>CGST (@Model.CGST%)</th>
                    <td>@Model.TotalCGSTPrice?.ToString("C", new CultureInfo("hi-IN"))</td>
                </tr>
            }

            @if (Model.SGST != 0 || Model.SGST != null)
            {
                <tr>
                    <th>SGST (@Model.SGST%)</th>
                    <td>@Model.TotalSGSTPrice?.ToString("C", new CultureInfo("hi-IN"))</td>
                </tr>

                <tr>
                    <th>Without GST Price(₹)</th>
                    <td>@Model.WithoutGSTPrice?.ToString("C", new CultureInfo("hi-IN"))</td>
                </tr>
            }
            <tr>
                <th>Total Amount(₹)</th>
                <td>@Model.Total_Price.ToString("C", new CultureInfo("hi-IN"))</td>
            </tr>
            <tr>
                <th>Received Amount(₹)</th>
                <td>@Model.Receive_Amount.ToString("C", new CultureInfo("hi-IN"))</td>
            </tr>
            <tr>
                <th>Discount (₹)</th>
                <td>@Model.Discount?.ToString("C", new CultureInfo("hi-IN"))</td>
            </tr>
            <tr>
                <th>Receive Payment Method</th>
                <td>@Model.Payment_Method</td>
            </tr>

            @if (Model.Receive_Information_ID != null)
            {
                string baseAddress = "https://stock-manage-api-shree-ganesh-agro-ind.somee.com/";
                string Icon = Model.Bank_Icon;
                string BankIcon = baseAddress + Icon;

                <tr>
                    <input type="hidden" id="BankIcon" value="@BankIcon" />
                    <th> Bank Account No</th>
                    <td>XXXXX@(Model.Receive_Account_No.Substring(Model.Receive_Account_No.Length - 4)) <img src="@BankIcon" class="bank-icon" /></td>
                </tr>

                <tr>
                    <th>Account Holder Name</th>
                    <td>@Model.Account_Holder_Name</td>
                </tr>
            }

            <tr>
                <th>Deducted Amount(₹)</th>
                <td>@Model.Deducted_Amount.Value.ToString("C", new CultureInfo("hi-IN"))</td>
            </tr>

            <tr>
                <th>Is Full Amount Payment Received?</th>
                <td>@(Model.IsFullPaymentReceive.ToString())</td>
            </tr>

            @if (Model.IsFullPaymentReceive == "NO")
            {


                <tr>
                    <th>Remain Payment Date</th>
                    <td>@Model.Remain_Payment_Date?.ToString("dd-MM-yyyy")</td>
                </tr>
                <tr>
                    <th>Remain Amount(₹)</th>
                    <td>@Model.Receive_Remain_Amount?.ToString("C", new CultureInfo("hi-IN"))</td>
                </tr>
                <tr>
                    <th>Remain Payment Method</th>
                    <td>@Model.Remain_Payment_Method</td>
                </tr>

                @if (Model.Remain_Receive_Information_ID != 0 || Model.Remain_Receive_Information_ID != null)
                {
                    string baseAddress = "https://stock-manage-api-shree-ganesh-agro-ind.somee.com/";
                    string Icon = Model.Remain_Bank_Icon;
                    string BankIcon = baseAddress + Icon;

                    <tr>
                        <th> Remain Bank Account No</th>
                        <td>XXXXX@(Model.Receive_Remain_Account_No.Substring(Model.Receive_Remain_Account_No.Length - 4))  <img src="@BankIcon" class="bank-icon" /></td>
                    </tr>

                    <tr>
                        <th>Remain Account Holder Name</th>
                        <td>@Model.Remain_Account_Holder_Name</td>
                    </tr>


                }
            }

        </table>
    </div>
</div>